package com.luisfellipe.testalivro;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CT01SubmarinoTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private String pathChrome = "C:\\Selenium\\chromedriver.exe"; //Caminho do driver chrome
    
    @Before
    public void setUp() { //setup para googlechrome
        System.setProperty("webdriver.chrome.driver", pathChrome);
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        driver.manage().window().maximize();
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cT01Submarino() {
        // Test name: CT01Submarino
        // Step # | name | target | value
        // 1 | open | /categoria/livros | 
        driver.get("https://www.submarino.com.br/categoria/livros/");       
        // 3 | runScript | window.scrollTo(0,1800) | 
        js.executeScript("window.scrollTo(0,1800)");
        // 4 | click | xpath=//*[@id="content-middle"]/div[1]/div/div/section/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div[2]/a/section/div[1]/div/div/picture/img | 
        driver.findElement(By.xpath("//*[@id=\"content-middle\"]/div[1]/div/div/section/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div[2]/a/section/div[1]/div/div/picture/img")).click();
        // 5 | storeText | css=.Tr-sc-1wy23hs-3:nth-child(12) > .Td-sc-1wy23hs-5:nth-child(2) > .TextUI-sc-12tokcy-0 | isbn13
        vars.put("isbn13", driver.findElement(By.cssSelector(".Tr-sc-1wy23hs-3:nth-child(12) > .Td-sc-1wy23hs-5:nth-child(2) > .TextUI-sc-12tokcy-0")).getText());
        // 6 | click | css=.Tr-sc-1wy23hs-3:nth-child(13) > .Td-sc-1wy23hs-5:nth-child(2) | 
        driver.findElement(By.cssSelector(".Tr-sc-1wy23hs-3:nth-child(13) > .Td-sc-1wy23hs-5:nth-child(2)")).click();
        // 7 | storeText | css=.Tr-sc-1wy23hs-3:nth-child(13) > .Td-sc-1wy23hs-5:nth-child(2) > .TextUI-sc-12tokcy-0 | author
        vars.put("author", driver.findElement(By.cssSelector(".Tr-sc-1wy23hs-3:nth-child(13) > .Td-sc-1wy23hs-5:nth-child(2) > .TextUI-sc-12tokcy-0")).getText());
        // 8 | close |  | 
        driver.close();
    }
}
