package com.luisfellipe.testalivro;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CT02AmericanasTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private String pathChrome = "C:\\Selenium\\chromedriver.exe"; //Caminho do driver chrome

    @Before
    public void setUp() { //setup do googlechrome.
        System.setProperty("webdriver.chrome.driver", pathChrome);
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        driver.manage().window().maximize();
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cT02Americanas() {
        // Test name: CT02Americanas
        // Step # | name | target | value
        // 1 | open | https://www.americanas.com.br/ | 
        driver.get("https://www.americanas.com.br/");
        // 2 | click | id=h_search-input | 
        driver.findElement(By.id("h_search-input")).click();
        // 3 | runScript | window.scrollTo(0,0) | 
        js.executeScript("window.scrollTo(0,0)");
        // 4 | type | id=h_search-input | 9788501115553
        driver.findElement(By.id("h_search-input")).sendKeys("9788501115553");
        // 5 | click | css=#h_search-btn > .src-btn-ico | 
        driver.findElement(By.cssSelector("#h_search-btn > .src-btn-ico")).click();
        // 6 | runScript | window.scrollTo(0,1313) | 
        js.executeScript("window.scrollTo(0,1313)");
        // 7 | click | css=.src__Image-xr9q25-0 | 
        driver.findElement(By.cssSelector(".src__Image-xr9q25-0")).click();
        // 8 | runScript | window.scrollTo(0,800) | 
        js.executeScript("window.scrollTo(0,800)");
        // 9 | runScript | window.scrollTo(0,1259) | 
        js.executeScript("window.scrollTo(0,1259)");
        // 10 | runScript | window.scrollTo(0,1461) | 
        js.executeScript("window.scrollTo(0,1461)");
        // 11 | runScript | window.scrollTo(0,2400) | 
        js.executeScript("window.scrollTo(0,2400)");
        // 12 | storeText | css=.src__View-wbypax-3:nth-child(3) > .src__Text-wbypax-4:nth-child(2) | authorAm
        vars.put("authorAm", driver.findElement(By.cssSelector(".src__View-wbypax-3:nth-child(3) > .src__Text-wbypax-4:nth-child(2)")).getText());
        // 13 | close |  | 
        driver.close();
    }
}
