package com.luisfellipe.testalivro;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CT03AmazonTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private String pathChrome = "C:\\Selenium\\chromedriver.exe"; //Caminho do driver chrome

    @Before
    public void setUp() { //setup do googlechrome
        System.setProperty("webdriver.chrome.driver", pathChrome);
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        driver.manage().window().maximize();
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cT03Amazon() {
        // Test name: CT03Amazon
        // Step # | name | target | value
        // 1 | open | https://www.amazon.com/ | 
        driver.get("https://www.amazon.com/");
        // 2 | setWindowSize | 516x576 | 
        driver.manage().window().setSize(new Dimension(516, 576));
        // 3 | click | id=twotabsearchtextbox | 
        driver.findElement(By.id("twotabsearchtextbox")).click();
        // 4 | type | id=twotabsearchtextbox | 9788501115553
        driver.findElement(By.id("twotabsearchtextbox")).sendKeys("9788501115553");
        // 5 | sendKeys | id=twotabsearchtextbox | ${KEY_ENTER}
        driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ENTER);
        // 6 | mouseOver | css=#p_n_feature_twenty_browse-bin\/13054657011 .a-size-base | 
        {
            WebElement element = driver.findElement(By.cssSelector("#p_n_feature_twenty_browse-bin\\/13054657011 .a-size-base"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 7 | mouseOut | css=#p_n_feature_twenty_browse-bin\/13054657011 .a-size-base | 
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 8 | click | css=.s-image | 
        driver.findElement(By.cssSelector(".s-image")).click();
        // 9 | storeText | linkText=Holly Black | AuthorAmz
        vars.put("AuthorAmz", driver.findElement(By.linkText("Holly Black")).getText());
    }
}
